{{- if .Values.feedToken.externalSecret.create -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "prefixd.fullname" . }}
  labels:
    {{- include "prefixd.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    {{- toYaml .Values.feedToken.externalSecret.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "prefixd.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: FEED_TOKEN
      remoteRef:
        {{- toYaml .Values.feedToken.externalSecret.remoteRef | nindent 8 }}
{{- end }}
