apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valheim.fullname" . }}
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config.data }}
  {{- if and (not (kindIs "invalid" $v)) (ne (printf "%v" $v) "") }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
