apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-sentinel.fullname" . }}-headless
  labels:
    {{- include "redis-sentinel.redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis-port
      port: 6379
      targetPort: redis-port
      protocol: TCP
  selector:
    {{- include "redis-sentinel.redis.selectorLabels" . | nindent 4 }}
