# Default values for valheim.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/mbround18/valheim
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""


# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}


# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: gateway
    sectionName: http
    # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
  - chart-example.local
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

service:
  type: LoadBalancer
  port: 2456

persistence:
  enabled: true

  # If you want to use an existing PersistentVolumeClaim, specify its name here.
  # If this is set, the chart will not create a new PVC.
  # Example:
  # existingClaim: "my-pre-existing-valheim-pvc"
  existingClaim: ""

  # Settings for dynamic volume provisioning.
  # These are ignored if `existingClaim` is set.
  # For more info: https://kubernetes.io/docs/concepts/storage/storage-classes/
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  size: 10Gi

nodeSelector: {}

tolerations: []

affinity: {}

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""


config:
  # ConfigMap data
  data:
    TYPE: BepInEx
    PORT: 2456
    NAME: ''
    WORLD: ''
    PASSWORD: ''
    TZ: ''
    PUBLIC: 1
    AUTO_UPDATE: 1
    AUTO_UPDATE_SCHEDULE: '0 1 * * *'
    AUTO_BACKUP: 1
    AUTO_BACKUP_SCHEDULE: '*/15 * * * *'
    AUTO_BACKUP_REMOVE_OLD: 0
    AUTO_BACKUP_DAYS_TO_LIVE: 5
    AUTO_BACKUP_ON_UPDATE: 1
    AUTO_BACKUP_ON_SHUTDOWN: 1
    AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS: 1
    MODS: https://mydomain.com/mods.json
