apiVersion: v2
name: redis-sentinel
description: A Helm chart for deploying Redis Sentinel
# has to at least support the gateway api
kubeVersion: '>=1.30.0-0'
type: application

version: 1.0.0
appVersion: "8.2-alpine"
maintainers:
  - name: algo7
    url: https://github.com/algo7
