name: Create Stable Release

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

on:
  workflow_dispatch:
  push:
    tags:
      - '*-v*.*.*-v*.*.*' # chartName-appVersion-chartVersion


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Create Stable Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set Context Variables
        run: |
          REF="${{ github.ref_name }}"
          
          # Use cut with '-' as the delimiter (-d) and select the field number (-f)
          CHART_NAME=$(echo "$REF" | cut -d'-' -f1)
          APP_VERSION=$(echo "$REF" | cut -d'-' -f2)
          CHART_VERSION=$(echo "$REF" | cut -d'-' -f3)

          echo "CHART_NAME=$CHART_NAME" >> $GITHUB_ENV
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV
          echo "HELM_PACKAGE_PATH=${{ github.workspace }}/charts/$CHART_NAME" >> $GITHUB_ENV

      - name: Setup Helm
        uses: azure/setup-helm@v4.3.0

      - name: Package Helm Chart
        run: helm package $HELM_PACKAGE_PATH --version $CHART_VERSION --app-version $APP_VERSION --destination ${{ github.workspace }}

      # Login to GitHub Container Registry
      - name: Registry Login
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Publish Helm OCI Chart
        run: helm push ${{ github.workspace }}/${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository }}
        shell: bash
        env:
          HELM_EXPERIMENTAL_OCI: 1

      - name: Create Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${{ github.ref_name }}
          gh release create $TAG_NAME \
            ${{ github.workspace }}/${CHART_NAME}-${CHART_VERSION}.tgz \
            --generate-notes \
            --latest
